spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: woowa
          uri: ${WOOWA_IP}
          predicates:
            - Path=/woowa/**
        - id: delivery
          uri: ${DELIVERY_IP}
          predicates:
            - Path=/delivery/**
        - id: payment
          uri: ${PAYMENT_IP}
          predicates:
            - Path=/payment/**

logging:
  level:
    root: INFO
  file:
    name: /spring-log/application.log